apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-ddns.fullname" . }}
  labels:
    app: {{ include "cloudflare-ddns.name" . }}
  spec:
    type: {{ .Values.service.type }}
    ports:
    - port: {{ .Values.service.port }}
# I dont believe the below is needed.  I had grabbed some defaults I saw in the helm howto page, but this doesn't need targetport.
#       targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "cloudflare-ddns.name" . }}