apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-ddns.fullname" . }}
  labels:
    app: {{ include "cloudflare-ddns.name" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "cloudflare-ddns.name" . }}